//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITPM_Code_Complexity_Tool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int File_Id { get; set; }
        public string File_Path { get; set; }
        public string File_name { get; set; }
        public string File_Type { get; set; }
    }
}
